image: php:7.1

variables:
  PHP_MEMORY_LIMIT: "1024M"

cache:
  key: "${CI_PROJECT_ID}"
  untracked: false
  paths:
    - "vendor/"

stages:
  - analysis

before_script:
  - apt-get update -qq
  - apt-get install -qq -y zip unzip curl git >> /dev/null
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php --install-dir=/usr/bin --filename=composer
  - php -r "unlink('composer-setup.php');"

psr2:
  stage: analysis
  script:
    - composer global require "divante-ltd/pimcore-coding-standards":"dev-master" --no-interaction --prefer-dist --ignore-platform-reqs --quiet
    - php -d memory_limit=$PHP_MEMORY_LIMIT /root/.composer/vendor/bin/phpcs --config-set colors 1
    - php -d memory_limit=$PHP_MEMORY_LIMIT /root/.composer/vendor/bin/phpcs --extensions=php --standard=/root/.composer/vendor/divante-ltd/pimcore-coding-standards/Standards/Pimcore5/ruleset.xml ./src  -s

phpmd:
  stage: analysis
  script:
    - composer global require "phpmd/phpmd":"^2.6.0" --no-interaction --prefer-dist --ignore-platform-reqs --quiet
    - composer global require "divante-ltd/pimcore-coding-standards":"dev-master" --no-interaction --prefer-dist --ignore-platform-reqs --quiet
    - /root/.composer/vendor/bin/phpmd src text /root/.composer/vendor/divante-ltd/pimcore-coding-standards/Standards/Pimcore5/rulesetmd.xml

phpcpd:
  stage: analysis
  script:
    - composer global require "sebastian/phpcpd":"^3.0.0" --no-interaction --prefer-dist --ignore-platform-reqs --quiet
    - /root/.composer/vendor/bin/phpcpd src

phpdocblock:
  stage: analysis
  script:
    - composer global require "block8/php-docblock-checker":"^1.3.4" --no-interaction --prefer-dist --ignore-platform-reqs --quiet
    - /root/.composer/vendor/bin/phpdoccheck --directory=src

phploc:
  stage: analysis
  script:
    - composer global require "phploc/phploc":"^4.0.0" --no-interaction --prefer-dist --ignore-platform-reqs --quiet
    - /root/.composer/vendor/bin/phploc src
