imports:
    - { resource: config.yml }

# this cache is used during tests when setting up pimcore
pimcore:
    cache:
        pool_service_id: pimcore.cache.core.pool.array

doctrine:
    dbal:
        connections:
            default:
                host: mysql
                dbname: pimcoretest
                user: root
                password: pimcoretest
