services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false

    Divante\ClassificationstoreBundle\Command\ClassificationstoreImportCommand: ~
    Divante\ClassificationstoreBundle\Command\ClassificationstoreExportCommand: ~

    Divante\ClassificationstoreBundle\Import\Interfaces\ItemFactoryInterface:
        class: Divante\ClassificationstoreBundle\Import\ItemFactory

    Divante\ClassificationstoreBundle\Import\Interfaces\KeyFactoryInterface:
        class: Divante\ClassificationstoreBundle\Import\KeyFactory

    Divante\ClassificationstoreBundle\Import\Importer:
        public: true

    Divante\ClassificationstoreBundle\Export\Interfaces\ItemFactoryInterface:
      class: Divante\ClassificationstoreBundle\Export\ItemFactory

    Divante\ClassificationstoreBundle\Export\Interfaces\KeyFactoryInterface:
      class: Divante\ClassificationstoreBundle\Export\KeyFactory

    Divante\ClassificationstoreBundle\Export\Exporter:
        public: true

    Divante\ClassificationstoreBundle\Repository\StoreRepository:
        public: true

    Divante\ClassificationstoreBundle\Repository\CollectionRepository:
        public: true

    Divante\ClassificationstoreBundle\Repository\GroupRepository:
        public: true

    Divante\ClassificationstoreBundle\Repository\KeyRepository:
        public: true

    Divante\ClassificationstoreBundle\Component\FieldWrapperInterface:
        class: Divante\ClassificationstoreBundle\Component\FieldWrapper
        public: true

    Divante\ClassificationstoreBundle\Export\Item\Store:
        public: true

    Divante\ClassificationstoreBundle\Export\Item\Collection:
        public: true

    Divante\ClassificationstoreBundle\Export\Item\Group:
        public: true

    Divante\ClassificationstoreBundle\Export\Item\Key:
        public: true
